### ISSUE TITLE
mvn liberty:run failed to execute from finish directory

### ISSUE THREAD

**Issue by uniquejava** [OpenLiberty/guide-spring-boot#94] opened 2021-11-10 07:10 UTC
Logs as follows:

```
$ mvn liberty:run
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< org.springframework:guide-spring-boot >----------------
[INFO] Building guide-spring-boot 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- liberty-maven-plugin:3.3.4:run (default-cli) @ guide-spring-boot ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:21.0.0.11:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Running maven-compiler-plugin:compile
[INFO] Nothing to compile - all classes are up to date
[INFO] Running maven-resources-plugin:resources
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/cyper/github/guide-spring-boot/finish/src/main/resources
[INFO] skip non existing resourceDirectory /Users/cyper/github/guide-spring-boot/finish/src/main/resources
[INFO] Running liberty:create
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:21.0.0.11:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2112I: Re-using previously installed assembly.
[INFO] Copying 1 file to /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/cyper/github/guide-spring-boot/finish/src/main/liberty/config/server.xml.
[INFO] Running liberty:install-feature
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:21.0.0.11:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Running liberty:deploy
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:21.0.0.11:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp/usr/servers/defaultServer.
[INFO] Copying 1 file to /Users/cyper/github/guide-spring-boot/finish/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/cyper/github/guide-spring-boot/finish/src/main/liberty/config/server.xml.
[INFO] Found Spring Boot Uber JAR: /Users/cyper/github/guide-spring-boot/finish/target/guide-spring-boot-0.1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.393 s
[INFO] Finished at: 2021-11-10T15:05:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.3.4:run (default-cli) on project guide-spring-boot: An invocation of the springBootUtility command failed. The command is not available on the targeted Liberty runtime. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by uniquejava** [comment] 2021-11-10 07:29
Looks like some liberty features not installed when running `mvn liberty:package`

```
[INFO] Launching defaultServer (Open Liberty 21.0.0.11/wlp-1.0.58.cl211120211019-1900) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_261-b12 (en_US)
[INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for servlet-4.0
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for springboot-2.0
[INFO] [AUDIT   ] CWWKF0026I: The server defaultServer is ready to build a smaller package.
[INFO] [AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[INFO] [AUDIT   ] CWWKE0036I: The server defaultServer stopped after 0.91 seconds.

```

**Comment by uniquejava** [comment] 2021-11-10 07:58
I fixed this issue by installing the 2 missing features mannually.

```bash
cd target/liberty/wlp/bin
./featureUtility installFeature servlet-4.0 
./featureUtility installFeature springBoot-2.0
```

but why `liberty-maven-plugin` not install features automatically, do I miss something?

**Comment by gkwan-ibm** [comment] 2021-11-11 22:00
hi @uniquejava 

Yes, it is required to run `mvn package` first, and then `mvn liberty:run`. The `liberty-maven-plugin` should install the required features for you.

May I know which version of maven and jdk you used?
- run `mvn -version`

**Comment by uniquejava** [comment] 2021-11-13 00:25
@gkwan-ibm Thank you for your reply. Yes, after further reading the tutorial, I managed to install the missing features by just running `mvn package`, I thought `liberty:package` will install the dependencies required by the liberty and the `liberty:run` will start the server and it turns out not. I will just use `mvn package` next time.

The maven version is `3.6.3`

The JDK version now is `11.0.13`, but becoz my macOS default jdk version is 1.8, that could be one reason it fails at first, I will come back to this if I met this issue again.

**Comment by deftdawg** [comment] 2022-04-30 01:46
Going through my logs line by line trying to figure out why my app gives me `Error 404: SRVE0190E: File not found: /` at it's context root...   I see this in the logs... 
```
[INFO] [AUDIT   ] CWWKG0016I: Starting server configuration update.
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for servlet-4.0
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for jndi-1.0
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for jdbc-4.2
```

Rather than actually install the requested plugins, liberty just complains they're not there and carries on?!?  If liberty is incapable of doing the install after start-up, why not just have it restart or exit?  The behaviour of treating configuration like it's optional stuff makes no sense.

I'm using the liberty dev dashboard vscode plugin.

**Comment by gkwan-ibm** [comment] 2022-05-02 15:08
hi @deftdawg 
I cannot get the error messages when I clone the spring-boot guide, go to the finish directory, and run liberty:run. 
```
git clone https://github.com/openliberty/guide-spring-boot.git
cd guide-spring-boot/finish
./mvnw liberty:run
```
Instead, I get other error,
```
[WARNING] Spring Boot Uber JAR was not found in expected location: /Users/gkwan/tasks/CNAI/guides/testsite/spring-boot/prod/guide-spring-boot/finish/target/guide-spring-boot-0.1.0.jar
...
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.5.1:run (default-cli) on project guide-spring-boot: null: MojoExecutionException: NullPointerException -> [Help 1]
```
It is expected because this guide requires the spring-boot application. Run `mvn package` to download the spring-boot application and then run `liberty:run` goal.

Do you want to report another issue? Would you describe to us how to reproduce your problem/error messages?

**Comment by gkwan-ibm** [comment] 2023-01-23 22:51
hi @deftdawg we are closing this issue. You may reopen it with providing information on how to reproduce the problem/error messages.

**Closed as completed by gkwan-ibm** 2023-01-23 22:51 UTC
Labels: Needs member attention
